#Eureka server服务端口
server:
  port: 8761
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中作为服务的id标识(serviceId)
eureka:
  instance:
    hostname: EurekaServerA
  client:
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://EurekaServerB:8762/eureka/
    register-with-eureka: true
    fetch-registry: true #自己就是服务不需要从Eureka Server获取服务信息,默认为true，置为false